name: coding_cats
version: '1.0.0'
config-version: 2

profile: coding_cats

on-run-start:
  - "INSTALL mssql FROM community;"
  - "LOAD mssql;"
  - "ATTACH 'mssql://{{ env_var('MSSQL_USER') }}:{{ env_var('MSSQL_PASSWORD') }}@127.0.0.1:1433?database={{ env_var('MSSQL_DATABASE') }}' AS sql_server (TYPE MSSQL);"

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

seeds:
  coding_cats:
    raw_data:
      +column_types:
        id: INTEGER
        name: VARCHAR
        email: VARCHAR
        signup_date: DATE
        plan_type: VARCHAR
        amount: "DECIMAL(10,2)"
    plans:
      +column_types:
        plan_type: VARCHAR
        amount: "DECIMAL(10,2)"
        benefit: VARCHAR
    benefit_features:
      +column_types:
        benefit: VARCHAR
        email_support: BOOLEAN
        live_chat: BOOLEAN
        phone_support: BOOLEAN
        api_access: BOOLEAN
        custom_integrations: BOOLEAN
        sla_guarantee: BOOLEAN
